
"""Add sent_to_telegram to AiSignal

Revision ID: 09280b48e726
Revises: 20260223_0004
Create Date: 2026-02-24 03:00:56.860183
"""
from alembic import op
import sqlalchemy as sa


revision = '09280b48e726'
down_revision = '20260223_0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_to_telegram', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_signals', schema=None) as batch_op:
        batch_op.drop_column('sent_to_telegram')

    # ### end Alembic commands ###
