
"""add_telegram_agent_memory_audit_tables

Revision ID: 2abc13bf2891
Revises: 09280b48e726
Create Date: 2026-02-24 03:51:26.760017
"""
from alembic import op
import sqlalchemy as sa


revision = '2abc13bf2891'
down_revision = '09280b48e726'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_message_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('tool_calls_json', sa.JSON(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_message_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_message_log_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_message_log_created_at'), ['created_at'], unique=False)

    op.create_table('telegram_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('preferred_model_override', sa.String(length=64), nullable=True),
    sa.Column('preferred_style', sa.String(length=64), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=64), nullable=False),
    sa.Column('summary_context', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_sessions_chat_id'), ['chat_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_sessions_chat_id'))

    op.drop_table('telegram_sessions')
    with op.batch_alter_table('telegram_message_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_message_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_telegram_message_log_chat_id'))

    op.drop_table('telegram_message_log')
    # ### end Alembic commands ###
