
"""add_llm_tracking

Revision ID: 9852edfc3689
Revises: 20260223_0003
Create Date: 2026-02-23 13:48:04.996376
"""
from alembic import op
import sqlalchemy as sa


revision = '9852edfc3689'
down_revision = '20260223_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_task'), ['task'], unique=False)

    with op.batch_alter_table('youtube_channels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_youtube_channels_channel_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_youtube_channels_channel_id'))
        batch_op.create_index(batch_op.f('ix_youtube_channels_channel_id'), ['channel_id'], unique=True)

    with op.batch_alter_table('youtube_insights', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_youtube_insights_video_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_youtube_insights_video_id'))
        batch_op.create_index(batch_op.f('ix_youtube_insights_video_id'), ['video_id'], unique=True)

    with op.batch_alter_table('youtube_videos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_youtube_videos_video_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_youtube_videos_video_id'))
        batch_op.create_index(batch_op.f('ix_youtube_videos_video_id'), ['video_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youtube_videos_video_id'))
        batch_op.create_index(batch_op.f('ix_youtube_videos_video_id'), ['video_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_youtube_videos_video_id'), ['video_id'])

    with op.batch_alter_table('youtube_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youtube_insights_video_id'))
        batch_op.create_index(batch_op.f('ix_youtube_insights_video_id'), ['video_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_youtube_insights_video_id'), ['video_id'])

    with op.batch_alter_table('youtube_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youtube_channels_channel_id'))
        batch_op.create_index(batch_op.f('ix_youtube_channels_channel_id'), ['channel_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_youtube_channels_channel_id'), ['channel_id'])

    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_task'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_status'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_created_at'))

    op.drop_table('llm_calls')
    # ### end Alembic commands ###
